[pytest]

markers =
    faq: тесты Вопросов о важном
    order: тесты создания заказов
    navigation: тесты перехода по логотипам

addopts = -v -s --tb=short
testpaths = tests

log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S
